swagger: '2.0'
info:
  description: Api of constellation providing many services.
  version: 1.0.0
  title: Swagger Constellation
  contact:
    email: mamadou-abdoulaye.diop@etu.unice.fr
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost
basePath: /constellationServices
tags:
  - name: news
    description: Operations about news
schemes:
  - http
paths:
  '/news/{countryName}/{lang}':
    get:
      tags:
        - News
      summary: 'Get latest news '
      description: Get the latest of a country
      parameters:
        - in: path
          name: countryName
          description: The country we want to check news
          required: true
          type: string
        - in: path
          name: lang
          description: Language in which news should be displayed
          required: true
          type: string
          maxLength: 3
      responses:
        '200':
          description: Get latest news of the passed country
          schema:
            $ref: '#/definitions/News'
definitions:
  News:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      summary:
        type: string
      date:
        type: string
        format: date-time
      source:
        type: string
